# Generated by Django 4.0.5 on 2023-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
